events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    types {
        application/javascript js;
    }

    server {
        listen 80;
        server_name localhost;

        root /code;  # Chemin correct pour servir les fichiers
        index index.html index.php;  # Ajout de index.html

        # Serveur pour les fichiers statiques (ex: CSS, JS, images)
        location /assets/ {
            root /code;
            try_files $uri $uri/ =404;
        }

        # Traitement des fichiers PHP
        location ~ \.php$ {
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Route principale pour servir les fichiers HTML/PHP
        location / {
            try_files $uri $uri/ =404;
        }
    }
}
