events {}

http {
    include       mime.types;  # Inclut les types MIME par défaut
    default_type  application/octet-stream;

    # Ajout du type MIME pour les fichiers .js
    types {
        application/javascript js;
        # Vous pouvez ajouter d'autres types ici si nécessaire
    }

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;  # Racine des fichiers statiques
        index index.php;

        # Serveur pour les fichiers statiques (ajout du bloc pour /assets)
        location /assets/ {
            root /code;  # La racine des fichiers pour /assets
            try_files $uri $uri/ =404;  # Si le fichier n'existe pas, renvoie une erreur 404
        }

        # Configuration pour les fichiers PHP
        location ~ \.php$ {
            fastcgi_pass php:9000;  # Le service PHP écoute sur le port 9000
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Configuration pour la racine / (si besoin)
        location / {
            try_files $uri $uri/ =404;
        }
    }
}
